name: Daily dcjobs.com Scrape

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name }}
    
    - name: Install pipenv
      run: pipx install pipenv
    - uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install

    - name: Run Scraper
      run: pipenv run python scraper.py
    
    - name: Add and commit	
      run: |
        git add .	
        git config user.name "Automated"	
        git config user.email "actions@users.noreply.github.com"	
        git commit -m "Latest data" 	
    
    - name: Push	
      run: git push
